version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfiles/backend/Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app_db
      - DB_USER=app_db_user
      - DB_PASSWORD=app_db_password
      - DEBUG=1
    depends_on:
      - db

  node-frontend:
    container_name: node-frontend
    build:
      context: .
      dockerfile: Dockerfiles/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./reposter-react/src:/apps/reposter-react/src
      - node_modules:/reposter-react/node_modules

  db:
    image: postgres:16.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=app_db_user
      - POSTGRES_PASSWORD=app_db_password

volumes:
  db_data:
  dev-static-data:
  node_modules: