# Generated by Django 5.0.6 on 2024-06-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_socialaccounts_user_soc_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='linkedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='reddit',
            field=models.BooleanField(default=False),
        ),
    ]
