# Generated by Django 5.0.6 on 2024-06-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_post_linkedin_post_reddit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reddit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='soc_accounts',
        ),
        migrations.AddField(
            model_name='post',
            name='soc_accounts',
            field=models.ManyToManyField(blank=True, to='core.socialaccounts'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='reddit',
            field=models.BooleanField(default=False),
        ),
    ]
