# Generated by Django 5.0.6 on 2024-06-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usersocialaccountssettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersocialaccountssettings',
            old_name='created_at',
            new_name='access_token_create',
        ),
        migrations.RenameField(
            model_name='usersocialaccountssettings',
            old_name='access_token',
            new_name='access_token_status',
        ),
        migrations.RemoveField(
            model_name='usersocialaccountssettings',
            name='code',
        ),
        migrations.RemoveField(
            model_name='usersocialaccountssettings',
            name='refresh_token',
        ),
    ]
