# Generated by Django 5.0.6 on 2024-06-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_created_at_usersocialaccountssettings_access_token_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersocialaccountssettings',
            old_name='access_token_status',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='usersocialaccountssettings',
            old_name='access_token_create',
            new_name='access_token_expires_at',
        ),
        migrations.RemoveField(
            model_name='usersocialaccountssettings',
            name='status',
        ),
        migrations.AddField(
            model_name='usersocialaccountssettings',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usersocialaccountssettings',
            name='scope',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
