# Generated by Django 5.0.6 on 2024-06-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_access_token_status_usersocialaccountssettings_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialaccountssettings',
            name='id_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usersocialaccountssettings',
            name='token_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usersocialaccountssettings',
            name='access_token',
            field=models.TextField(blank=True),
        ),
    ]
