# Generated by Django 5.0.6 on 2024-06-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_usersocialaccountssettings_id_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersocialaccountssettings',
            name='access_token',
        ),
    ]
