# Generated by Django 5.0.6 on 2024-06-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_usersocialaccountssettings_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialaccountssettings',
            name='access_token',
            field=models.TextField(blank=True),
        ),
    ]
