# Generated by Django 5.0.6 on 2024-06-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_usersocialaccountssettings_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocialaccountssettings',
            name='id_token',
            field=models.TextField(blank=True),
        ),
    ]
