# Generated by Django 5.0.6 on 2024-06-29 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_usersocialaccountssettings_id_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialaccountssettings',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
