# Generated by Django 5.0.6 on 2024-06-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_usersocialaccountssettings_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialaccountssettings',
            name='id_token',
            field=models.TextField(blank=True),
        ),
    ]
