# Generated by Django 5.0.6 on 2024-07-01 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_linkedinuserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinuserinfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usersocialaccountssettings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
