# Generated by Django 5.0.6 on 2024-07-02 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_linkedinuserinfo_created_at_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccounts',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.post'),
            preserve_default=False,
        ),
    ]
