# Generated by Django 5.0.6 on 2024-07-06 22:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_reddituserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddituserinfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
