# Generated by Django 5.0.6 on 2024-07-08 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_reddituserinfo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='soc_accounts',
        ),
        migrations.RemoveField(
            model_name='socialaccounts',
            name='post_id',
        ),
        migrations.AddField(
            model_name='socialaccounts',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='core.post'),
            preserve_default=False,
        ),
    ]
