# Generated by Django 5.0.6 on 2024-07-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_socialaccounts_post_postserviceevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postserviceevents',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
